name: 'Setup Angular Environment'
description: 'Generate environment file and build Angular app'

inputs:
  angular-env:
    description: 'Angular environment'
    required: true
  build-config:
    description: 'Build configuration'
    required: true
  api-url:
    description: 'API URL'
    required: true
  google-maps-api-key:
    description: 'Google Maps API Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash
      run: |
        echo "GOOGLE_MAPS_API_KEY=${{ inputs.google-maps-api-key }}" > .env.${{ inputs.build-config }}
        echo "API_URL=${{ inputs.api-url }}" >> .env.${{ inputs.build-config }}
        cat .env.${{ inputs.build-config }}

    - name: Generate environment file from .env file
      shell: bash
      env:
        API_URL: ${{ inputs.api-url }}
        GOOGLE_MAPS_API_KEY: ${{ inputs.google-maps-api-key }}
      run: npx cross-env ANGULAR_ENV=${{ inputs.angular-env }} node set-env.js
